SESSION_MODE_VIEW = "view"
SESSION_MODE_CONTROL = "control"
SESSION_MODES = (SESSION_MODE_VIEW, SESSION_MODE_CONTROL)

GRANT_KIND_OPEN = "open"
GRANT_KIND_PREEMPT = "preempt"
GRANT_KIND_REVOKE = "revoke"
GRANT_KINDS = (GRANT_KIND_OPEN, GRANT_KIND_PREEMPT, GRANT_KIND_REVOKE)

SUBJECT_KIND_TEACHER = "teacher"
SUBJECT_KIND_ADMIN = "admin"
SUBJECT_KINDS = (SUBJECT_KIND_TEACHER, SUBJECT_KIND_ADMIN)

ROOM_TYPE_IT_LAB = "it_lab"

ENROLLMENT_PORT = 8743
RFB_TLS_PORT = 5901
HEARTBEAT_INTERVAL_SECONDS = 30
ENROLLMENT_TIMEOUT_SECONDS = 10

MSG_TYPE_REGISTER = "register"
MSG_TYPE_HEARTBEAT = "heartbeat"
MSG_TYPE_ENROLLMENT_RESULT = "enrollment_result"
MSG_TYPE_CONFLICT_REJECTION = "conflict_rejection"
MSG_TYPE_HEALTH_REPORT = "health_report"
MSG_TYPE_BROKER_SESSION_REQUEST = "broker_session_request"
MSG_TYPE_LOGIN_REQUEST = "login_request"
MSG_TYPE_LOGIN_RESULT = "login_result"
